function [ results,   resultsWtr,  StFig,     uStFig,     ...
           LnFig,     WFig,        wTempFig,  wndSpdFig,  ...
           metaTFig,  metaBFig,    thermDFig, SthermDFig, ...
           SmetaBFig, SmetaTFig,   SuStFig,   SLnFig,     ...
           SWFig,     N2Fig,       SN2Fig,    T1Fig,      ...
           ST1Fig ] = Run_LA_WPS(...
            bthFileName, lvlFileName, wndFileName, wtrFileName, salFileName,   ...
            outputResolution, totalDepth, windHeight, windAveraging,           ...
            layerAveraging, outlierWindow, maxWaterTemp,  minWaterTemp,        ...
            maxWindSpeed,  minWindSpeed, metaMinSlope,  mixedTempDifferential, ...
            figRes, figUnits, figWidth, figHeight, leftMargin, rightMargin,    ...
            topMargin, botMargin, fontName, fontSize, heatMapMin, heatMapMax)
  %
  pltMods = struct('figUnits',    figUnits,             ...
                   'figWidth',    num2str(figWidth),    ...
                   'figHeight',   num2str(figHeight),   ...
                   'leftMargin',  num2str(leftMargin),  ...
                   'rightMargin', num2str(rightMargin), ...
                   'topMargin',   num2str(topMargin),   ...
                   'botMargin',   num2str(botMargin),   ...
                   'figType',     'png',                ...
                   'figRes',      num2str(figRes),      ...
                   'fontName',    fontName,             ...
                   'fontSize',    num2str(fontSize),    ...
                   'heatMapMin',  num2str(heatMapMin),  ...
                   'heatMapMax',  num2str(heatMapMax));

  inFileNames = struct('bthFileName', bthFileName, ...
                       'wndFileName', wndFileName, ...
                       'wtrFileName', wtrFileName);

  % null inputs are encoded as NaN
  if ~isnan(salFileName)
      inFileNames.salFileName = salFileName;
  end
  if ~isnan(lvlFileName)
      inFileNames.lvlFileName = lvlFileName;
  end

  outFileNames = struct('results',    [tempname '.out'], ...
                        'resultsWtr', [tempname '.out'], ...
                        'StFig',      [tempname '.out'], ...
                        'uStFig',     [tempname '.out'], ...
                        'LnFig',      [tempname '.out'], ...
                        'WFig',       [tempname '.out'], ...
                        'wTempFig',   [tempname '.out'], ...
                        'wndSpdFig',  [tempname '.out'], ...
                        'metaTFig',   [tempname '.out'], ...
                        'metaBFig',   [tempname '.out'], ...
                        'thermDFig',  [tempname '.out'], ...
                        'SthermDFig', [tempname '.out'], ...
                        'SmetaBFig',  [tempname '.out'], ...
                        'SmetaTFig',  [tempname '.out'], ...
                        'SuStFig',    [tempname '.out'], ...
                        'SLnFig',     [tempname '.out'], ...
                        'SWFig',      [tempname '.out'], ...
                        'N2Fig',      [tempname '.out'], ...
                        'SN2Fig',     [tempname '.out'], ...
                        'T1Fig',      [tempname '.out'], ...
                        'ST1Fig',     [tempname '.out']);

  LA({'St', 'uSt', 'Ln', 'W', 'wTemp', 'wndSpd', 'metaT', 'metaB', 'thermD', ...
      'SthermD', 'SmetaB', 'SmetaT', 'SuSt', 'SLn', 'SW', 'N2', 'SN2', 'T1', ...
      'ST1'},                                                                ...
    outputResolution, totalDepth, windHeight, windAveraging, layerAveraging, ...
    outlierWindow, maxWaterTemp, minWaterTemp, maxWindSpeed, minWindSpeed,   ...
    metaMinSlope, mixedTempDifferential, inFileNames, outFileNames, pltMods, ...
    1, 1);

  results     = outFilenames.results
  resultsWtr  = outFilenames.resultsWtr
  StFig       = outFilenames.StFig
  uStFig      = outFilenames.uStFig
  LnFig       = outFilenames.LnFig
  WFig        = outFilenames.WFig
  wTempFig    = outFilenames.wTempFig
  wndSpdFig   = outFilenames.wndSpdFig
  metaTFig    = outFilenames.metaTFig
  metaBFig    = outFilenames.metaBFig
  thermDFig   = outFilenames.thermDFig
  SthermDFig  = outFilenames.SthermDFig
  SmetaBFig   = outFilenames.SmetaBFig
  SmetaTFig   = outFilenames.SmetaTFig
  SuStFig     = outFilenames.SuStFig
  SLnFig      = outFilenames.SLnFig
  SWFig       = outFilenames.SWFig
  N2Fig       = outFilenames.N2Fig
  SN2Fig      = outFilenames.SN2Fig
  T1Fig       = outFilenames.T1Fig
  ST1Fig      = outFilenames.ST1Fig
end